<?php

/**
 * @file
 * This is the module sales.
 */

use Drupal\Core\Database\Database;

function commodity_theme() {
  return [
    'commodity_register_form' => [
      'render element' => 'form',
    ],
    'commodity_update_form' => [
      'render element' => 'form',
    ],
    'commodity_delete_form' => [
      'render element' => 'form',
    ],
    'commodity_index' => [
      'variables' => [
      ],
      'render element' => 'form',
    ],
  ];
}