<?php

/**
 * @file
 * This is the module sales.
 */

use Drupal\Core\Database\Database;

function employee_theme() {
  return [
    'employee_register_form' => [
      'render element' => 'form',
    ],
    'employee_update_form' => [
      'render element' => 'form',
    ],
    'employee_delete_form' => [
      'render element' => 'form',
    ],
    'employee_list' => [
      'variables' => [
      ],
      'render element' => 'form',
    ],
  ];
}